server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/users
    username: ${username}
    password: ${password}
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update

#security:
#  jwtSecretKey: 2d20517c794c53617a3a6e4b6b61367b6222204d6d64402c6375496d475f6244
#
application:
  security:
    jwt:
      secret-key: ${secret_key}
#      expiration: 60000 # 1 Minute
#      expiration: 1800000 # 30 Minutes
#      expiration: 3600000 # 1 Hour
#      expiration: 43200000 # 12 Hours
#      expiration: 86400000 # 1 day
      expiration: 604800000 # 7 days
      user-generator: ${user_generator}
