server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/users
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      secret-key: ${secret_key}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
